### ISSUE TITLE
World generation does not work

### ISSUE THREAD

**Issue by SeedersShit** [Colonova/ColonovasTechMod#4]
World generation does not work for any ores, mined out 8 full chunks with a quarry and no ores from mod appeared.

**Comment by Colonova** [comment]
I put the data files in the wrong directory and the entire system needs to be rewritten from scratch because it's a mess anyway and I over complicated things.

**Comment by Colonova** [comment]
Fixed in dev, will be added to next commit however still need to rewrite it
